version: "3.7"
services:
  solr:
    image: george.azurecr.io/solr:7.5.0
    environment:
      - test:test
    volumes:
      - C:/docker/solr:C:/solr/server/solr/mydata
  sitecore:
    image: george.azurecr.io/sitecore:9.2-1903
    depends_on:
      #- identity
      - xconnect
      - solr
    ports:
      - "2222:80"
    env_file:
      - variables.env
    volumes:
      - C:/docker/sitecore/logs:C:/inetpub/wwwroot/App_Data/logs
      - C:/docker/sitecore/certificates:C:/certificates
      - C:/docker/license:C:/license
  # identity:
  #   image: identity:9.2-1903
  #   ports:
  #     - "3333:80"
  #   env_file:
  #     - variables.env
  #   volumes:
  #     - C:/docker/license:C:/license
  xconnect:
    image: george.azurecr.io/xconnect:9.2-1903
    depends_on:
      - xconnect-indexworker
      - xconnect-processingengine
      - xconnect-maengine
    ports:
      - "4444:80"
    env_file:
      - variables.env
    volumes:
      - C:/docker/xconnect/logs:C:/inetpub/wwwroot/App_Data/logs
      - C:/docker/xconnect/certificates:C:/certificates
      - C:/docker/license:C:/license
  xconnect-indexworker:
    image: george.azurecr.io/xconnect.indexworker:9.2-1903
    depends_on: solr
    env_file:
      - variables.env
    volumes:
      - C:/docker/xconnect.indexworker/logs:C:/app/App_Data/logs
      - C:/docker/license:C:/license
  xconnect-maengine:
    image: george.azurecr.io/xconnect.maengine:9.2-1903
    env_file:
      - variables.env
    volumes:
      - C:/docker/xconnect.maengine/logs:C:/app/App_Data/logs
      - C:/docker/xconnect.maengine/certificates:C:/certificates
      - C:/docker/license:C:/license
  xconnect-processingengine:
    image: george.azurecr.io/xconnect.processingengine:9.2-1903
    env_file:
      - variables.env
    volumes:
      - C:/docker/xconnect.processingengine/logs:C:/app/App_Data/logs
      - C:/docker/xconnect.processingengine/certificates:C:/certificates
      - C:/docker/license:C:/license
