generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: sitecore-admin
  files:
  - sitecore-adminpassword.txt
- name: sitecore-database
  files:
  - sitecore-databaseusername.txt
  - sitecore-databasepassword.txt  
  - sitecore-databaseservername.txt
  - sitecore-collection-shardmapmanager-database-password.txt
  - sitecore-collection-shardmapmanager-database-username.txt
  - sitecore-core-database-password.txt
  - sitecore-core-database-username.txt
  - sitecore-exm-master-database-password.txt
  - sitecore-exm-master-database-username.txt
  - sitecore-forms-database-password.txt
  - sitecore-forms-database-username.txt
  - sitecore-marketing-automation-database-password.txt
  - sitecore-marketing-automation-database-username.txt
  - sitecore-master-database-password.txt
  - sitecore-master-database-username.txt
  - sitecore-messaging-database-password.txt
  - sitecore-messaging-database-username.txt
  - sitecore-processing-engine-storage-database-password.txt
  - sitecore-processing-engine-storage-database-username.txt
  - sitecore-processing-engine-tasks-database-password.txt
  - sitecore-processing-engine-tasks-database-username.txt
  - sitecore-processing-pools-database-password.txt
  - sitecore-processing-pools-database-username.txt
  - sitecore-processing-tasks-database-password.txt
  - sitecore-processing-tasks-database-username.txt
  - sitecore-reference-data-database-password.txt
  - sitecore-reference-data-database-username.txt
  - sitecore-reporting-database-password.txt
  - sitecore-reporting-database-username.txt
  - sitecore-web-database-password.txt
  - sitecore-web-database-username.txt
  - sitecore-database-elastic-pool-name.txt
- name: sitecore-identitycertificate
  files:
  - sitecore-identitycertificate.txt
  - sitecore-identitycertificatepassword.txt
- name: sitecore-license
  files:
  - sitecore-license.txt
- name: sitecore-identity
  files:
  - sitecore-identitysecret.txt
- name: sitecore-telerik
  files:
  - sitecore-telerikencryptionkey.txt
- name: sitecore-reporting
  files:
  - sitecore-reportingapikey.txt
- name: sitecore-solr
  files:
  - sitecore-solr-connection-string.txt
- name: sitecore-solr-xdb
  files:
  - sitecore-solr-connection-string-xdb.txt
- name: global-cd-tls
  files:
    - tls/global-cd/tls.key
    - tls/global-cd/tls.crt
  type: kubernetes.io/tls
- name: global-cm-tls
  files:
    - tls/global-cm/tls.key
    - tls/global-cm/tls.crt
  type: kubernetes.io/tls
- name: global-id-tls
  files:
    - tls/global-id/tls.key
    - tls/global-id/tls.crt
  type: kubernetes.io/tls